# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b69f5970b530ff8199aadb27784bc8d19f4fa47758163312f6e009e6be1891a6b4a2eb6fd973878a78645a3473c076cc95baf89a673f53b1f9148bc930352920

test:
  secret_key_base: 2e5dd803d94ea25133d467519c04d1e231fc9f390f251f76011cfce91d801a586744053d47b1827105d5b5435b72aad33a75fa44e1f4d999fd48859e49753aa3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
